### ISSUE TITLE
Phantom not going out of invis

### ISSUE THREAD

**Issue by redst0neer** [lemonypancakes/origins-bukkit#1]
when i am using the phantom while im not using the ability i am still invisble

**Comment by SwagPancakes** [comment]
Can you please provide your server version and can you give the screenshot before and after you used the ability ?

**Comment by SwagPancakes** [comment]
This is how it is supposed to look like when your ability is toggled off and you're supposed to burn when exposed to the sun.
![Screenshot_4](https://user-images.githubusercontent.com/67215956/144745280-8056b264-3b8d-4a2e-8196-6a2c46d2e839.png)
And this when using the ability is toggled on.
![Screenshot_5](https://user-images.githubusercontent.com/67215956/144745356-bd6476e1-af55-4fed-84c3-9792e48befe8.png)
