### ISSUE TITLE
✨Fancy Cooldowns Idea

### ISSUE THREAD

**Issue by Lebyy** [lemonypancakes/origins-bukkit#16]
### Minecraft Server's Version and Software

1.18.1

### Plugin's Version

Build 2-RELEASE

### Bug Description

Would it be possible for you to make the cooldowns fancy? Like make them appear on a bossbar, action bar and etc..
It would look really good and easy to understand cooldowns.

### To Reproduce

Not a bug.

**Comment by lemonypancakes** [comment]
80d09b6f493eaad639b4d0dff46c63875843b788

**Comment by Lebyy** [comment]
> [80d09b6](https://github.com/lemonypancakes/origins-bukkit/commit/80d09b6f493eaad639b4d0dff46c63875843b788)

Woooo! Thank you so much for this amazing plugin and all the hardwork you put onto it bringing this wholesome update to the public!

**Comment by lemonypancakes** [comment]
I will make it more customizable next update.
