### ISSUE TITLE
Different Action To Toggle origin abilities

### ISSUE THREAD

**Issue by ITSJUSTJOSH41** [lemonypancakes/origins-bukkit#18]
### Minecraft Server's Version and Software

1.18.1

### Plugin's Version

[Origins-Bukkit Build 2-RELEASE]

### Bug Description

Is there a way to make it so that instead of having to swap items and crouch you could just crouch and punch to toggle/use the abilities? I was wondering because I use geyser on my server which allows bedrock players to join and since there is no way to swap items on bedrock, there is no way to toggle on the abilities. Is there anyway I could re-code the plugin toe change this? Thanks!

### To Reproduce

On a controller there is no way to swap items so you cannot toggle on the abilities for the origins.

**Comment by Lebyy** [comment]
Oo yes could check for if Punching + Sneaking, I'll make a branch in my repo where can add this feature
