### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by JustSkeppYT** [lemonypancakes/origins-bukkit#19]
### Minecraft Server's Version and Software

1.18.1-R0.1-SNAPSHOT

### Plugin's Version

2-Release

### Bug Description

Unsure why,, but the command doesn't work and returns an error.
![image](https://user-images.githubusercontent.com/68767065/153198543-8559b8e7-0f71-46cb-809a-634073af411d.png)
![image](https://user-images.githubusercontent.com/68767065/153198562-55e92452-1988-4b93-a431-832c28e4755a.png)

### To Reproduce

The command completely does not work

**Comment by Maks1116** [comment]
If you did use reload command or any plugin enabling/disabling plugin then this is why its not working. Try to restart server.
