### ISSUE TITLE
Code not working on my server

### ISSUE THREAD

**Issue by StrikerLPB** [lemonypancakes/origins-bukkit#20]
### Minecraft Server's Version and Software

I was using Minecraft Paper 1.18.1 but I switched to Spigot 1.18.1 for this plugin

### Plugin's Version

Origins-Bukkit [1.17-1.18.1] Build 2-RELEASE

### Bug Description

Idk if there is a certain code I must translate
 to for it to work, but I use Minehut server hosting. i downloaded the plugin and uploaded it to the server files but when i check the code it shows a bunch of question mark icons instead of code. I believe Minehut uses just English Skript but I'm not for sure.. Is there any way to get code that works?
 
 ![Screenshot 2022-02-09 161644](https://user-images.githubusercontent.com/99367787/153299580-d33bfc70-42de-48b9-a141-f8037272382f.png)
![Screenshot 2022-02-09 161700](https://user-images.githubusercontent.com/99367787/153299591-c284c013-84ec-44c3-bf56-40b04a30ea7e.png)

### To Reproduce

N/A

### Additional Information

Anything helps. I'm just a youtuber trying to get this plugin to work for my server

**Comment by oliver408i** [comment]
That is normal. Don't open the plugin jar. Just run the server
