### ISSUE TITLE
Blazeborn origins spawns outside border

### ISSUE THREAD

**Issue by oliver408i** [lemonypancakes/origins-bukkit#21]
### Minecraft Server's Version and Software

1.18.1 purplur
Latest version of plugin

### Plugin's Version

Latest version (2 - RELEASE)

### Bug Description

If you have a non-default worldborder size, blazeborn spawns outside the worldborder

### To Reproduce

Set the worldborder to 100 or something
Log in and choose blazeborn
Get stuck outside the border

**Comment by Lebyy** [comment]
Can reproduce this on my server.
