### ISSUE TITLE
it keeps saying theres an eternal error when i attempt to use the command

### ISSUE THREAD

**Issue by ihwqefiefgyuig** [lemonypancakes/origins-bukkit#23]
### Minecraft Server's Version and Software

![unknown](https://user-images.githubusercontent.com/86742245/158270749-b138bd13-d9a9-4060-b453-4244f408ddd2.png)

### Plugin's Version

RELEASE

### Bug Description

It says eternal error when i do the command /origins .
In the log it says its disabled and i cannot go to the config.

### To Reproduce

I made a server for 1.18.1 and added the plugin and then I started the server and did the command then it says there is an external error. I went to the log and in the error it says "plugin disabled" and I tried going to the files to the plugin to see if i can enable it there but I wasn't able to open it.

**Comment by Lebyy** [comment]
Do you have the extra plug-ins required installed aswell?
