### ISSUE TITLE
Elytra not appearing + Odd visual(?) bug in GUI

### ISSUE THREAD

**Issue by Tempest-5ky** [LemonyPancakes/Origins-Bukkit#42]
### Minecraft Server's Version and Software

Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)

### Plugin's Version

v2.3.1

### Bug Description

Just a couple things, there may be more but I haven't done super extensive testing yet.
First thing is that all the origins and their power entries have these bizarre symbols before them:
![image](https://user-images.githubusercontent.com/99220350/178839657-960ee8f8-a280-4335-823e-ca97251fd3c4.png)

Second thing is that the Elytrian's elytra power does not seem to be working, as no elytra is visible on the player or in its inventory, nor will an invisible one deploy when falling. No errors visible in the logs, the plugin just reports that it has loaded successfully without issues. Lemoncommonlib and Protocollib are both up to date.

### To Reproduce

Join a server with the plugin active. If you look at the origin descriptions and names in the gui, all are preceded by a bizarre symbol that resembles an accented capital A.
Select the Elytrian origin, you'll notice that though the launch ability works, no elytra is equipped and you will fall to your death.

**Comment by LemonyPancakes** [comment]
Do the elytra glide power work? Try sneaking + item swapping. The elytra not appearing is intentional as there is no way to have both elytra and armor in bukkit.

**Comment by LemonyPancakes** [comment]
Try deleting the origins-bukkit folder in your main world's data packs folder.

**Comment by Tempest-5ky** [comment]
Glide does not work, no. What do you mean by item swapping? Pressing shift
+ F? Tried that, if I’m in midair when I do it it launches me and if I’m on
the ground it puts me into elytra flight position but does not actually
work for flying, if I go off a cliff with it I just fall to my death.

**Comment by Tempest-5ky** [comment]
Tried that, didn’t fix it!

**Comment by LemonyPancakes** [comment]
Try joining this test server 157.90.176.214:25652.

**Comment by Tempest-5ky** [comment]
Accidentally closed it, my bad!
Seems to work fine there, thank you. Most likely I was just thrown off by the unfamiliar controls, being used to having a normal elytra!
If i may ask, what was the "races" screen on that server from? Seems like a similar plugin and i'm intrigued!

**Comment by LemonyPancakes** [comment]
> Accidentally closed it, my bad! Seems to work fine there, thank you. Most likely I was just thrown off by the unfamiliar controls, being used to having a normal elytra! If i may ask, what was the "races" screen on that server from? Seems like a similar plugin and i'm intrigued!

secret
