### ISSUE TITLE
Not A bug but, Is there any way to edit origins and make new ones?

### ISSUE THREAD

**Issue by notmerlin** [LemonyPancakes/Origins-Bukkit#46]
### Minecraft Server's Version and Software

Minecraft 1.17 Paper

### Plugin's Version

2.3.6

### Bug Description

Title Says all.

### To Reproduce

none

### Additional Information

none

**Comment by LemonyPancakes** [comment]
Wiki on how to create one coming very soon https://origins-bukkit.lemonypancakes.me

**Comment by notmerlin** [comment]
>
