### ISSUE TITLE
Kelp blocks toggles merling night vision 

### ISSUE THREAD

**Issue by Kelbbie** [LemonyPancakes/Origins-Bukkit#47]
### Minecraft Server's Version and Software

1.19.1 Petal

### Plugin's Version

Latest

### Bug Description

When swimming through kelp the merling's night vision toggles on and off

### To Reproduce

Swim through kelp blocks with the merling class

**Comment by LemonyPancakes** [comment]
I am already aware of that issue, will be fixed next version. Anyways, thank you very much for the sponsor <3.

**Comment by Kelbbie** [comment]
<3

**Comment by Kelbbie** [comment]
Just reopening to confirm you are aware about this one as well. While in bubbles from magma blocks or soul sand night vision toggles
