### ISSUE TITLE
When I start the server this happens

### ISSUE THREAD

**Issue by YouKnwNothing** [LemonyPancakes/Origins-Bukkit#56]
### Minecraft Server's Version and Software

1.19.2 java version

### Plugin's Version

Origins-Bukkit 2.3.8, LemonCommonLib 2.2.2, Latest protocollib

### Bug Description

![image](https://user-images.githubusercontent.com/92229785/185520459-a9541dab-355e-46b1-b91b-28dbd3e1d6f7.png)

### To Reproduce

Start the server.

**Comment by LemonyPancakes** [comment]
try deleting the origins-bukkit.zip and/or origins-bukkit that is located in your world's datapacks folder.

**Comment by YouKnwNothing** [comment]
> try deleting the origins-bukkit.zip and/or origins-bukkit that is located in your world's datapacks folder.

Got it working goated lemonypancakes, when you bringing phantom back?
