### ISSUE TITLE
Let us customize the Origins again?

### ISSUE THREAD

**Issue by YouKnwNothing** [LemonyPancakes/Origins-Bukkit#59]
### Minecraft Server's Version and Software

1.19.2/paper

### Plugin's Version

2.3.8

### Bug Description

New version is worse than 1.18.

### To Reproduce

Install the plugin.

### Additional Information

Can you let us edit the origins at least?? Going to be honest 1.18 origins 500x better I have no clue why you removed so many things. My merlin players don't even want to play because they cant even last long on land anymore. Lmk when you get back on this plugin.

**Comment by LemonyPancakes** [comment]
you can? just decompress the zip file and put the contents inside a folder (you can name it anything although I recommend naming the folder "origins-bukkit") inside your server world's datapack folder.

**Comment by Anon121334** [comment]
Idk what happened, when I started editing the powers it worked like magic. But for some unknown reason it keeps replacing the new .zip in datapacks with the stock one with the old power data, any help will be greatly appreciated

**Comment by Anon121334** [comment]
i found a way to edit the datapack, for anyone wanting the solution just lmk it's a tad complicated

**Comment by ddomino007** [comment]
> i found a way to edit the datapack and keep the changes made, for anyone wanting the solution just lmk it's a tad complicated

can you just post the solution then?

**Comment by Anon121334** [comment]
> > i found a way to edit the datapack and keep the changes made, for anyone wanting the solution just lmk it's a tad complicated
> 
> can you just post the solution then?

sorry my bad

I found a better method than the first, what you do is you have to download the jar from the website. once you have the jar you have to change it from a .jar to .zip, look up how you can do it in file explorer, then unzip then go to datapacks and unzip and make your changes, then zip up origins-bukkit and remove the unzipped version, then zip the whole file up(the whole plugin files) then turn it back into a jar. what happens is that when you put the origins-bukkit folder in datapacks it gets deleted and the origins-bukkit from inside the jar replaces it as the default, so what we are doing is modifying the actual default so automatically it places our modified origins-bukkit file into the datapacks folder. hope this helped :> also if you are so kind can you please post any new powers you made? im not good at making them :< also if you can please, i also have an issue with giving an origin a certain potion effect at all times with no particles, if you know how to can you please tell me or post the power? thank you and i hop i helped!
